[build]
  command = "npm install"
  functions = "functions"

[[redirects]]
  from = "/"
  to = "/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/upload"
  to = "/upload-page.html"
  status = 200
  force = true

[[redirects]]
  from = "/view"
  to = "/view.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
